---
- hosts: lab-debian
  become: yes
  remote_user: ansible
  tasks:
  - name: Instalando o nginx
    apt:
      name: nginx
      state: latest
      update_cache: yes
  - name: Iniciando o nginx
    service:
      name: nginx
      state: started
  - name: Copiando index.html personalizado
    template:
      src: files/nginx/index.html.j2
      dest: /var/www/html/index.html
  - name: Copiando nginx.conf
    copy:
      src: files/nginx/nginx.conf
      dest: /etc/nginx/nginx.conf
    notify: Restartando o Nginx
  handlers:
  - name: Restartando o Nginx
    service:
      name: nginx
      state: restarted