---
- name: Limpa o arquivo /etc/hosts
  shell: echo '' > /etc/hosts
  tags: hosts

- name: Configuracao do arquivo /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item.ip }} {{ item.fqdn }} {{ item.alias }}"
  with_items:
    - { ip: '127.0.0.1', fqdn: 'localhost.localdomain', alias: 'localhost' }
    - { ip: '192.168.109.129', fqdn: 'devops.dexter.com.br', alias: 'devops' }
    - { ip: '192.168.109.133', fqdn: 'testing.dexter.com.br', alias: 'testing' }
    - { ip: '192.168.109.132', fqdn: 'homolog.dexter.com.br', alias: 'homolog' }
    - { ip: '192.168.109.135', fqdn: 'balancer.dexter.com.br', alias: 'balancer' }
    - { ip: '192.168.109.134', fqdn: 'webserver01.dexter.com.br', alias: 'webserver01' }
    - { ip: '192.168.109.130', fqdn: 'webserver02.dexter.com.br', alias: 'webserver02' }
    - { ip: '192.168.109.131', fqdn: 'database.dexter.com.br', alias: 'database' }
    - { ip: '172.18.0.101', fqdn: 'ansible-server.dexter.com.br', alias: 'ansible-server' }
    - { ip: '172.18.0.102', fqdn: 'chef-server.dexter.com.br', alias: 'chef-server' }
    - { ip: '172.18.0.103', fqdn: 'chef-workstation.dexter.com.br', alias: 'chef-workstation' }
  tags: hosts
